version: "2.0"

services:
  app:
    build:
      context: ./docker/
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
        - ./:/var/www
    environment:
        - "APP_NAME=my Network"
    networks:
      - myNetwork

  web:
    build:
      context: ./docker/
      dockerfile: web.dockerfile
    ports:
      - "80:80"
    working_dir: /var/www
    networks:
      - myNetwork
    volumes_from:
      - app

  redis:
    image: redis:latest
    ports:
        - "6379:6379"
    networks:
      - myNetwork

  beanstalkd:
    build:
      context: ./docker/
      dockerfile: beanstalkd.dockerfile
    networks:
      - myNetwork
    ports:
      - "11300:11300"

  postgres:
    image: postgres:10.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: trabajos_remoto
      POSTGRES_USER: trabajos_remoto
      POSTGRES_PASSWORD: secret
    networks:
      - myNetwork

networks:
  myNetwork:
    external:
      name: myNetwork




